[tool.poetry]
name = "litellm"
version = "1.16.19"
description = "Library to easily interface with LLM API providers"
authors = ["BerriAI"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.9.7, <3.12"
openai = ">=1.0.0"
python-dotenv = ">=0.2.0"
tiktoken = ">=0.4.0"
importlib-metadata = ">=6.8.0"
tokenizers = "*"
click = "*"
jinja2 = "^3.1.2"
certifi = "^2023.7.22"
aiohttp = "*"
requests = "^2.31.0"

uvicorn = {version = "^0.25.0", optional = true}
fastapi = {version = "^0.104.1", optional = true}
backoff = {version = "*", optional = true}
pyyaml = {version = "^6.0", optional = true}
rq = {version = "*", optional = true}
orjson = {version = "^3.9.7", optional = true}
streamlit = {version = "^1.29.0", optional = true}
langchain = {version = "^0.1.0", optional = true}
boto3 = {version = "^1.34.15", optional = true}
google-generativeai = {version = "^0.3.2", optional = true}
google-cloud-aiplatform = {version = "^1.39.0", optional = true}
redis = {version = "^5.0.1", optional = true}
anthropic = {version = "^0.9.0", optional = true}
asyncio = {version = "^3.4.3", optional = true}
cohere = {version = "^4.40", optional = true}
langfuse = {version = "^2.5.0", optional = true}
prisma = {version = "^0.11.0", optional = true}

# Missing due to conflict:
# - traceloop-sdk
# - baseten

[tool.poetry.extras]
proxy = [
    "uvicorn",
    "fastapi",
    "backoff",
    "pyyaml",
    "rq",
    "orjson",
]

extra_proxy = [
    "prisma",
    "azure-identity",
    "azure-keyvault-secrets",
    "google-cloud-kms",
    "streamlit",
    "resend"
]


[tool.poetry.scripts]
litellm = 'litellm:run_server'

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
black = "^23.12.0"
pytest = "^7.4.3"
mypy = "^1.8.0"
pytest-async = "^0.1.1"
numpydoc = "^1.6.0"
setuptools = "^69.0.3"

[build-system]
requires = ["poetry-core", "wheel"]
build-backend = "poetry.core.masonry.api"

[tool.commitizen]
version = "1.16.19"
version_files = [
    "pyproject.toml:^version"
]

