ignore = ["F405", "E402", "F401", "E501", "F403"]
extend-select = ["E501"]
line-length = 120
select = ["PLR0915"]  
exclude = ["litellm/types/*", "litellm/__init__.py", "litellm/proxy/example_config_yaml/*"]

[pylint]
max-statements = 100
