model_list:
 - model_name: "gpt-3.5-turbo"
   litellm_params:
    model: azure/chatgpt-v-2
    api_key: os.environ/AZURE_API_KEY
    api_base: http://0.0.0.0:8090
    rpm: 3
    
litellm_settings:
  num_retries: 0

router_settings:
  routing_strategy: usage-based-routing-v2 # 👈 KEY CHANGE
  redis_host: os.environ/REDIS_HOST
  redis_password: os.environ/REDIS_PASSWORD
  redis_port: os.environ/REDIS_PORT

credential_list:
  - credential_name: default_azure_credential
    credential_values:
      api_key: os.environ/AZURE_API_KEY  # Load from environment
      api_base: os.environ/AZURE_API_BASE
      api_version: "2023-05-15"
    credential_info:
      description: "Production credentials for EU region"
      use_in_pass_through: true
      custom_llm_provider: "azure"

