model_list:
  - model_name: text-embedding-3-large
    litellm_params:
      model: openai/text-embedding-3-large
      api_key: os.environ/OPENAI_API_KEY
      tags: ["openai"]
  - model_name: text-embedding-3-large
    litellm_params:
      model: azure/text-embedding-3-large
      api_base: https://does-not-matter/
      api_key: os.environ/AZURE_API_KEY
      api_version: "2025-01-01-preview"
      tags: ["azure-openai"]

router_settings:
  enable_tag_filtering: True

custom_llm_provider_settings:
  - custom_llm_provider: azure
    litellm_params:
      api_key: os.environ/AZURE_API_KEY
      api_base: os.environ/AZURE_API_BASE

