model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
  - model_name: anthropic-claude
    litellm_params:
      model: anthropic.claude-3-sonnet-20240229-v1:0


general_settings:
  enable_jwt_auth: True 
  litellm_jwtauth:
    user_roles_jwt_field: "resource_access.litellm-test-client-id.roles"
    user_allowed_roles: ["basic_user"] # roles that map to an 'internal_user' role on LiteLLM 
    enforce_rbac: true # if true, will check if the user has the correct role to access the model + endpoint
  
  role_permissions: # control what models + endpointsare allowed for each role
    - role: internal_user
      models: ["anthropic-claude"]
      allowed_endpoints: ["/v1/chat/completions"]
  
  