model_list:
  # GPT-4 Turbo Models
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
  - model_name: rerank-model
    litellm_params:
      model: jina_ai/jina-reranker-v2-base-multilingual
  - model_name: anthropic-vertex
    litellm_params:
      model: vertex_ai/claude-3-5-sonnet-v2
      vertex_ai_project: "adroit-crow-413218"
      vertex_ai_location: "us-east5"  
  - model_name: openai-gpt-4o-realtime-audio
    litellm_params:
      model: openai/gpt-4o-realtime-preview-2024-10-01
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  success_callback: ["langsmith"]