model_list:
  - model_name: fake-openai-endpoint
    litellm_params:
      model: openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
  - model_name: "text-embedding-3-small"
    litellm_params:
      model: text-embedding-3-small
      api_key: os.environ/OPENAI_API_KEY
  - model_name: claude-opus-4-20250514
    litellm_params:
      model: anthropic/claude-opus-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY

litellm_settings:
  cache: true