model_list:
  - model_name: gpt-3.5-turbo-end-user-test
    litellm_params:
      model: gpt-3.5-turbo
      region_name: "eu"
    model_info:
      id: "1"
  - model_name: gpt-3.5-turbo-end-user-test
    litellm_params:
      model: gpt-3.5-turbo
      timeout: 2
      num_retries: 0
  - model_name: anthropic-claude
    litellm_params:
      model: claude-3-5-haiku-20241022
  - model_name: groq/*
    litellm_params:
      model: groq/*
      api_key: os.environ/GROQ_API_KEY
      mock_response: Hi!
  - model_name: deepseek/*
    litellm_params:
      model: deepseek/*
      api_key: os.environ/DEEPSEEK_API_KEY
