model_list:
  - model_name: fake-claude-endpoint
    litellm_params:
      model: anthropic.claude-3-sonnet-20240229-v1:0
      api_base: https://exampleopenaiendpoint-production.up.railway.app
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID

general_settings:
  alerting: ["webhook"]

litellm_settings:
  cache: True

  num_retries: 0
  allowed_fails: 10 # cooldown model if it fails > 1 call in a minute. 
  cooldown_time: 30 # how long to cooldown model if fails/min > allowed_fails

  redact_user_api_key_info: false

  default_team_settings: 
    - team_id: "7e8784f2-6712-44aa-855b-b7a7ce0bab2a"
      success_callbacks: ["langfuse"]
      langfuse_public_key: "pk-lf-b3db7e8e-c2f6-4fc7-825c-a541a8fbe003"
      langfuse_secret: "sk-lf-b11ef3a8-361c-4445-9652-12318b8596e4"
      langfuse_host: "https://us.cloud.langfuse.com"