model_list:
  - model_name: "gpt-4o-azure"
    litellm_params:
      model: azure/gpt-4o
      api_key: os.environ/AZURE_API_KEY
      api_base: os.environ/AZURE_API_BASE
  - model_name: "gpt-4o-mini-openai"
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: "openai/*"
    litellm_params:
        model: openai/*
        api_key: os.environ/OPENAI_API_KEY
  - model_name: "bedrock-nova"
    litellm_params:
      model: us.amazon.nova-pro-v1:0
  - model_name: "gemini-2.0-flash"
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: openrouter_model
    litellm_params:
      model: openrouter/openrouter_model
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: http://0.0.0.0:8090
  - model_name: "claude-3-7-sonnet"
    litellm_params:
      model: databricks/databricks-claude-3-7-sonnet
      api_key: os.environ/DATABRICKS_API_KEY
      api_base: os.environ/DATABRICKS_API_BASE
  - model_name: "gemini/gemini-2.0-flash"
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: "prod/claude-3-5-sonnet-20240620"
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_key: os.environ/ANTHROPIC_API_KEY
    model_info:
      input_cost_per_token: 0.000006
      output_cost_per_token: 0.00003
      cache_creation_input_token_cost: 0.0000075
      cache_read_input_token_cost: 0.0000006

litellm_settings:
  num_retries: 0
  callbacks: ["prometheus"]

files_settings:
  - custom_llm_provider: gemini
    api_key: os.environ/GEMINI_API_KEY