model_list:
  - model_name: "gemini-2.0-flash"
    litellm_params:
      model: vertex_ai/gemini-2.0-flash
      vertex_project: my-project-id
      vertex_location: us-central1
  - model_name: "gpt-4o-mini-openai"
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  num_retries: 0
  check_provider_endpoint: true
  cache: true

files_settings:
  - custom_llm_provider: gemini
    api_key: os.environ/GEMINI_API_KEY

general_settings:
  store_prompts_in_spend_logs: true