environment_variables:
  LANGFUSE_HOST: d6JemN4HDPlLfO3XK2GrMpjWcVx1s6FbUQXA6mRSqEzPwyc+RGjnAqghHZ+YxC4sk1TeEGau/VtRpS+MXm9PQh00
  LANGFUSE_PUBLIC_KEY: og65/+RZK1zRarsZCdhVjO04Lvy3NEhFECwB6+ICv+fhm4jxjxurNcLvDLDOe6q9GZj/X3jPjy2vltHHh1/++jgmwmjTJ/tOBUrv8wVC2p4S0Vw=
  LANGFUSE_SECRET_KEY: CMArAIf3uwkBT3/uZCxvFyWrt9gICu8UvyofB2kgzlmoCEonBZCG19ZR0rmesQoQc0WquYGPrFVWGSIKbA1acW4iQTPoO0YO1beA/ME5YfJeVA==
general_settings:
  alerting:
  - slack
  allow_user_auth: true
  enable_jwt_auth: true
  litellm_jwtauth:
    admin_jwt_scope: litellm_proxy_admin
    org_id_jwt_field: azp
    public_key_ttl: os.environ/LITELLM_PUBLIC_KEY_TTL
    user_id_jwt_field: sub
  master_key: sk-1234
  proxy_batch_write_at: 5
  store_model_in_db: True // set via environment variable - os.environ["STORE_MODEL_IN_DB"]
    = "True"
litellm_settings:
  service_callback:
  - prometheus_system
  success_callback:
  - prometheus
  - langfuse
  upperbound_key_generate_params:
    max_budget: os.environ/LITELLM_UPPERBOUND_KEYS_MAX_BUDGET
model_list:
- litellm_params:
    api_base: https://openai-function-calling-workers.tasslexyz.workers.dev/
    api_key: my-fake-key
    model: openai/my-fake-model
    rpm: 10
    stream_timeout: 0.001
  model_name: fake-openai-endpoint
- litellm_params:
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    api_version: 2023-07-01-preview
    model: azure/chatgpt-v-2
    stream_timeout: 0.001
  model_name: azure-gpt-3.5
- litellm_params:
    model: text-completion-openai/gpt-3.5-turbo-instruct
  model_name: gpt-instruct
router_settings:
  enable_pre_call_checks: true
  redis_host: os.environ/REDIS_HOST
  redis_password: os.environ/REDIS_PASSWORD
  redis_port: os.environ/REDIS_PORT
  routing_strategy: usage-based-routing-v2
