model_list:
  - model_name: azure.text-embedding-ada-002
    litellm_params:
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      model: azure/azure-embedding-model
    model_info:
      access_groups:
      - shared-models
      base_model: azure/text-embedding-ada-002
      mode: embedding
    


router_settings:
  routing_strategy: usage-based-routing-v2
  disable_cooldowns: True
