model_list:
  - model_name: gpt-4
    litellm_params:
      model: openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
      tags: ["free"] # :point_left: Key Change
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4o
      mock_response: "litellm.RateLimitError"

router_settings:
  enable_tag_filtering: True # 👈 Key Change
