model_list:
  - model_name: fake-openai-endpoint
    litellm_params:
      model: openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/

  - model_name: custom_whisper_nrt
    litellm_params:
      model: openai/fake
      api_base: http://0.0.0.0:8090/v1
      api_key: dummy
      my_own_param: "value"
    model_info:
      mode: audio_transcription

 
# litellm_settings:
#   cache: true
#   success_callback: ["langfuse"]
#   failure_callback: ["langfuse"]
#   alerting: ["slack"]
