model_list:
 - model_name: "gpt-4o"
   litellm_params:
    model: azure/chatgpt-v-2
    api_key: os.environ/AZURE_API_KEY
    api_base: http://0.0.0.0:8090
    rpm: 3
 - model_name: "gpt-4o-mini-openai"
   litellm_params:
    model: gpt-4o-mini
    api_key: os.environ/OPENAI_API_KEY
 - model_name: "openai/*"
   litellm_params:
    model: openai/*
    api_key: os.environ/OPENAI_API_KEY
 - model_name: "bedrock-nova"
   litellm_params:
    model: us.amazon.nova-pro-v1:0


files_settings:
  - custom_llm_provider: gemini
    api_key: os.environ/GEMINI_API_KEY
