model_list:
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
      api_base: http://0.0.0.0:8090
  - model_name: deepseek-r1
    litellm_params:
      model: bedrock/deepseek_r1/arn:aws:bedrock:us-west-2:888602223428:imported-model/bnnr6463ejgf

      
litellm_settings:
  callbacks: ["prometheus"]
  # custom_prometheus_metadata_labels: ["metadata.foo", "metadata.bar"]
