model_list:
  - model_name: gpt-3.5-turbo-testing
    litellm_params:
      model: gpt-3.5-turbo
      rpm: 3
  - model_name: anthropic-claude
    litellm_params:
      model: claude-3-5-haiku-20241022
  - model_name: groq/*
    litellm_params:
      model: groq/*
      api_key: os.environ/GROQ_API_KEY
      mock_response: Hi!
  - model_name: deepseek/*
    litellm_params:
      model: deepseek/*
      api_key: os.environ/DEEPSEEK_API_KEY

litellm_settings:
  num_retries: 0

router_settings:
  routing_strategy: usage-based-routing-v2 
  redis_host: os.environ/REDIS_HOST
  redis_password: os.environ/REDIS_PASSWORD
  redis_port: os.environ/REDIS_PORT
