model_list:
  - model_name: mlp-genai-npe-eastus-gpt-4o-mini-batch
    litellm_params:
      custom_llm_provider: azure
      model: gpt-4o-mini
      api_version: "2024-10-21"
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
    model_info:
      mode: batch

files_settings:
  - custom_llm_provider: azure
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    api_version: "2024-10-21"
