model_list:
  - model_name: 'stability.stable-diffusion-3.5-large'
    litellm_params:
      model: 'bedrock/stability.sd3-5-large-v1:0'
      aws_region_name: 'us-west-2'

  - model_name: 'stability.stable-image-ultra'
    litellm_params:
      model: 'bedrock/stability.stable-image-ultra-v1:1'
      aws_region_name: 'us-west-2'