model_list:
  - model_name: fake-openai-endpoint
    litellm_params:
      model: openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/

  - model_name: custom_whisper_nrt
    litellm_params:
      model: openai/fake
      api_base: http://0.0.0.0:8090/v1
      api_key: dummy
      my_own_param: "value"
    model_info:
      mode: audio_transcription

  - model_name: "text-mini-o4-mini"
    litellm_params:
      model: azure/o_series/webinterfaceo4-mini
      api_key: 04d22fb7e9ad4d9c8afe7c6abf97a6fc
      api_version: 2025-01-01-preview
      api_base: https://krris-m2f9a9i7-eastus2.openai.azure.com
  - model_name: "text-mini-o1-mini"
    litellm_params:
      model: azure/o_series/web-interface-o1-mini
      api_key: 04d22fb7e9ad4d9c8afe7c6abf97a6fc
      api_version: 2025-01-01-preview
      api_base: https://krris-m2f9a9i7-eastus2.openai.azure.com
 
# litellm_settings:
#   cache: true
#   success_callback: ["langfuse"]
#   failure_callback: ["langfuse"]
#   alerting: ["slack"]
