model_list:
  - model_name: "gemini/*"
    litellm_params:
      model: "gemini/*"


# used for the /cachedContent and vertexAI native endpoints
default_vertex_config:
  vertex_project: "adroit-crow-413218"
  vertex_location: "us-central1"