model_list:
  - model_name: fake-openai-endpoint
    litellm_params:
      model: openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
  - model_name: ollama-qwen
    litellm_params:
      model: ollama_chat/qwen2:0.5b
      api_base: http://localhost:11434
