model_list:
  - model_name: "fake-openai-endpoint"
    litellm_params:
      model: openai/gpt-4o

general_settings:    
    alerting: ["slack"]
    alert_to_webhook_url: {
      "budget_alerts": ["https://hooks.slack.com/services/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"]
    }
    alerting_args:
       budget_alert_ttl: 10
       log_to_console: true