model_list:
  - model_name: "fake-openai-endpoint"
    litellm_params:
      model: aiohttp_openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app
      input_cost_per_token: "0.0001"
      output_cost_per_token: "0.0001"
  - model_name: "fake-openai-endpoint-2"
    litellm_params:
      model: aiohttp_openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app
      input_cost_per_token: "0.0001"
      output_cost_per_token: "0.0001"




