model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-5
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://exampleopenaiendpoint-production.up.railway.app/


litellm_settings:
  callbacks: ["prometheus"]
  service_callback: ["prometheus_system"]
