model_list:
  - model_name: multimodalembedding@001
    litellm_params:
      model: vertex_ai/multimodalembedding@001
      vertex_project: "adroit-crow-413218"
      vertex_location: "us-central1"
      vertex_credentials: "adroit-crow-413218-a956eef1a2a8.json"
  - model_name: text-embedding-ada-002
    litellm_params:
      model: openai/text-embedding-ada-002                          # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  drop_params: True
  callbacks: ["otel"]
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

