model_list:
  - model_name: "fake-openai-endpoint"
    litellm_params:
      model: openai_like/any
      api_base: https://example-openai-endpoint.onrender.com
      api_key: "ishaan"

general_settings: 
  master_key: sk-1234 