model_list:
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-flash-lite-preview-06-17
      api_key: os.environ/GEMINI_API_KEY
  - model_name: "anthropic/*"
    litellm_params:
      model: "anthropic/*"
      api_key: os.environ/ANTHROPIC_API_KEY

mcp_servers:
  deepwiki_mcp:
    url: "https://mcp.deepwiki.com/mcp"
    transport: "http"

general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true

litellm_settings:
  callbacks: ["langfuse", "datadog"]