model_list:
  - model_name: "fake-openai-endpoint"
    litellm_params:
      model: aiohttp_openai/gpt-4o-mini
      api_key: any 
      api_base: https://exampleopenaiendpoint-production.up.railway.app

