model_list:
  - model_name: fake-openai-endpoint-all-users
    litellm_params:
      model: openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/

