model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
  - model_name: fake-anthropic-endpoint
    litellm_params:
      model: anthropic/fake
      api_base: https://exampleanthropicendpoint-production.up.railway.app/

litellm_settings:
  callbacks: ["datadog"] # will log success & failures 
  service_callbacks: ["datadog"] # will log DB fails / exceptions 
  turn_off_message_logging: True # will redact message / response content 