model_list:
  - model_name: db-openai-endpoint
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/

general_settings:
  alerting: ["slack"]


