model_list:
  - model_name: model-1
    litellm_params:
      model: openai/model-1
      api_key: os.environ/OPENAI_API_KEY_MODEL_1
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
  - model_name: model-2
    litellm_params:
      model: openai/model-2
      api_key: os.environ/OPENAI_API_KEY_MODEL_2
      api_base: https://exampleopenaiendpoint-production.up.railway.app/

general_settings:
  key_management_system: "aws_secret_manager"
  key_management_settings:
    hosted_keys: [
      "OPENAI_API_KEY_MODEL_1",
      "OPENAI_API_KEY_MODEL_2",
    ]
    primary_secret_name: "litellm_secrets"
