model_list:
  - model_name: "fake-openai-endpoint"
    litellm_params:
      model: openai_like/any
      api_base: https://exampleopenaiendpoint-production-c715.up.railway.app
      api_key: "ishaan"

general_settings: 
  master_key: sk-1234 