model_list:
  - model_name: "fake-openai-endpoint"
    litellm_params:
      model: openai/any
      api_base: https://exampleopenaiendpoint-production.up.railway.app
      api_key: "ishaan"

general_settings: 
  master_key: sk-1234 
  alerting: ["slack"]
  alerting_threshold: 0.0000001