model_list:
  - model_name: bad-model-config
    litellm_params:
      model: openai/my-fake-model
      api_key: my-fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
      timeout: 0.0001
  - model_name: fake-openai-endpoint-5
    litellm_params:
      model: openai/my-fake-model
      api_key: my-fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
      timeout: 1

router_settings:
  fallbacks: [
      {
          "bad-model-config": ["fake-openai-endpoint-5"]
      }
  ]

litellm_settings:
  constants: {
    SINGLE_DEPLOYMENT_TRAFFIC_FAILURE_THRESHOLD: 1
  }
