model_list:
  - model_name: llava-hf
    litellm_params:
      model: openai/llava-hf/llava-v1.6-vicuna-7b-hf
      api_base: http://localhost:8000
      api_key: fake-key
    model_info:
      supports_vision: True
general_settings:
  master_key: sk-1234
  default_team_disabled: true

litellm_settings:
  success_callback: ["prometheus"]

