model_list:
  - model_name: fake-azure-endpoint
    litellm_params:
      model: openai/429
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app


general_settings:
  master_key: sk-1234
  default_team_disabled: true