name: Publish Prisma Migrations

on:
  push:
    paths:
      - 'schema.prisma'  # Check root schema.prisma
    branches:
      - litellm_dev_03_25_2025_p3

jobs:
  publish-migrations:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: temp_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Add shadow database service
      postgres_shadow:
        image: postgres:14
        env:
          POSTGRES_DB: shadow_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install prisma
          pip install python-dotenv

      - name: Generate Initial Migration if None Exists
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/temp_db"
          DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/temp_db"
          SHADOW_DATABASE_URL: "postgresql://postgres:postgres@localhost:5433/shadow_db"
        run: |
          # Create migrations directory if it doesn't exist
          mkdir -p deploy/migrations
          
          # Create migration_lock.toml if it doesn't exist
          if [ ! -f "deploy/migrations/migration_lock.toml" ]; then
            echo 'provider = "postgresql"' > deploy/migrations/migration_lock.toml
          fi
          
          # Check if migrations exist
          if [ -z "$(ls -A deploy/migrations/2* 2>/dev/null)" ]; then
            echo "No existing migrations found, creating baseline..."
            VERSION=$(date +%Y%m%d%H%M%S)
            
            # Create baseline directory
            mkdir -p deploy/migrations/${VERSION}_initial
            
            # Generate baseline migration
            prisma migrate diff \
              --from-empty \
              --to-schema-datamodel schema.prisma \
              --shadow-database-url "${SHADOW_DATABASE_URL}" \
              --script > deploy/migrations/${VERSION}_initial/migration.sql
              
            echo "Initial migration generated at $(date -u)" > deploy/migrations/${VERSION}_initial/README.md
          fi

      - name: Compare and Generate Migration
        if: success()
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/temp_db"
          DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/temp_db"
          SHADOW_DATABASE_URL: "postgresql://postgres:postgres@localhost:5433/shadow_db"
        run: |
          # Create temporary migration workspace
          mkdir -p temp_migrations
          
          # Copy existing migrations (will not fail if directory is empty)
          cp -r deploy/migrations/* temp_migrations/ 2>/dev/null || true
          
          VERSION=$(date +%Y%m%d%H%M%S)
          
          # Generate diff against existing migrations or empty state
          prisma migrate diff \
            --from-migrations temp_migrations \
            --to-schema-datamodel schema.prisma \
            --shadow-database-url "${SHADOW_DATABASE_URL}" \
            --script > temp_migrations/migration_${VERSION}.sql
          
          # Check if there are actual changes
          if [ -s temp_migrations/migration_${VERSION}.sql ]; then
            echo "Changes detected, creating new migration"
            mkdir -p deploy/migrations/${VERSION}_schema_update
            mv temp_migrations/migration_${VERSION}.sql deploy/migrations/${VERSION}_schema_update/migration.sql
            echo "Migration generated at $(date -u)" > deploy/migrations/${VERSION}_schema_update/README.md
          else
            echo "No schema changes detected"
            exit 0
          fi

      - name: Verify Migration
        if: success()
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/temp_db"
          DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/temp_db"
          SHADOW_DATABASE_URL: "postgresql://postgres:postgres@localhost:5433/shadow_db"
        run: |
          # Create test database
          psql "${SHADOW_DATABASE_URL}" -c 'CREATE DATABASE migration_test;'
          
          # Apply all migrations in order to verify
          for migration in deploy/migrations/*/migration.sql; do
            echo "Applying migration: $migration"
            psql "${SHADOW_DATABASE_URL}" -f $migration
          done

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update prisma migrations"
          title: "Update Prisma Migrations"
          body: |
            Auto-generated migration based on schema.prisma changes.
            
            Generated files:
            - deploy/migrations/${VERSION}_schema_update/migration.sql
            - deploy/migrations/${VERSION}_schema_update/README.md
          branch: feat/prisma-migration-${{ env.VERSION }}
          base: litellm_dev_03_25_2025_p3 